# Generated by Django 5.0.1 on 2024-01-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='foto',
            field=models.ImageField(default='couch.png', upload_to=''),
        ),
    ]
