# Generated by Django 5.0.1 on 2024-01-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_body_product_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='body',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
    ]
